#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : electric-fence
Version  : 2.2.5
Release  : 2
URL      : http://archive.ubuntu.com/ubuntu/pool/universe/e/electric-fence/electric-fence_2.2.5.tar.gz
Source0  : http://archive.ubuntu.com/ubuntu/pool/universe/e/electric-fence/electric-fence_2.2.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: electric-fence-lib
Requires: electric-fence-license
Patch1: build.patch

%description
This is Electric Fence 2.2
Electric Fence is a different kind of malloc() debugger. It uses the virtual
memory hardware of your system to detect when software overruns the boundaries
of a malloc() buffer. It will also detect any accesses of memory that has
been released by free(). Because it uses the VM hardware for detection,
Electric Fence stops your program on the first instruction that causes
a bounds violation. It's then trivial to use a debugger to display the
offending statement.

%package lib
Summary: lib components for the electric-fence package.
Group: Libraries
Requires: electric-fence-license = %{version}-%{release}

%description lib
lib components for the electric-fence package.


%package license
Summary: license components for the electric-fence package.
Group: Default

%description license
license components for the electric-fence package.


%prep
%setup -q -n electric-fence
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539285967
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1539285967
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/electric-fence
cp COPYING %{buildroot}/usr/share/doc/electric-fence/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libefence.so.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/electric-fence/COPYING
